### ISSUE TITLE
Issue with preferences schema

### ISSUE THREAD

**Issue by JEverhart383** [knocklabs/knock-flutter#19]
Reposted from customer Slack:
I am unable to manage conditional preferences in flutter due to a bug in
preferences.dart  _workflowPreferencesFromJson
When the preferences for a category consist of just conditions not defining channelType preferences the fromJson for the preferences crashes as the method requires the field to be a _ChannelTypesJson (json['channel_types']) and a _ConditionsJson  at the same time (json['conditions'])
This is how i update the conditions:
final settings = WorkflowPreferenceSetting(
            channelTypePreferences: {},
            conditions: [
              PreferenceCondition(
                variable: 'actor.id',
                operator: 'equal_to',
                argument: username,
              ),
            ],
          );

   await _knockRepository.knock.preferences().set(SetPreferencesProperties(
            channelTypes: {},
            workflows: {},
            categories: {
              'social_employer_feed': settings
            },
          ));
Do we have to update the preferences differently to make this work?
![image (31)](https://github.com/knocklabs/knock-flutter/assets/7818951/cf327bac-6a6e-44c9-add7-a353823fc389)

**Comment by matgar26** [comment]
This issue is fixed with version 0.1.4
