### ISSUE TITLE
Errors are just logged as "Instance of 'ApiError'

### ISSUE THREAD

**Issue by flodaniel** [knocklabs/knock-flutter#23]
We use sentry in our flutter app to track crashes and we see these kind of reports, making it impossible for us to know what went wrong:

![image](https://github.com/knocklabs/knock-flutter/assets/6661557/f87fc79b-1d7a-488c-a5fd-46e432158aab)

I am not 100% sure how to resolve this. Maybe implementing `toString()` would help?

**Comment by flodaniel** [comment]
Tagging @matgar26 as you fixed our previous issue. A simple toString() would probably do the trick but you guys know your error objects the best! :)

**Comment by matgar26** [comment]
@flodaniel thanks for brining this to my attention. I will look into this now and should have a fix today.

**Comment by matgar26** [comment]
@flodaniel I pushed out a fix for this in v0.1.6

Could you let me know whether or not this solves the issue?

**Comment by flodaniel** [comment]
Hi @matgar26,
we now have 0.1.6 in production and we get better errors. E.g.:
```
ApiError: ApiResponse(status: 500, statusCode: StatusCode.error, body: null, error: ClientException with SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = api.knock.app, port = 61246,
```
Thank you!

**Comment by flodaniel** [comment]
One more thing.
If you could also export your `ApiResponse` and `ApiError` classes that would be great. Right now I have to import them like this:

```
// ignore: implementation_imports
import 'package:knock_flutter/src/model/api_response.dart';

```
